print("Hello World!")
Name = ('Umar')
print("My name is", Name,end='.')
age = ('25')
print('I am', age, 'years old')
print(max(10, 20))
Name2 = input('Enter your girlfriend\'s name: ')
age2 = input('Enter your girlfriend\'s age: ')
print('My gf name is', Name2, 'and she is', age2, 'years old')
