shopping_list = ['eggs', 'milk', 'bread']
print(shopping_list)
shopping_list.append('coffee')
print(shopping_list)
shopping_list.append('sugar')
print(shopping_list)
shopping_list.reverse()
print(shopping_list)
shopping_list.sort()
print(shopping_list)
shopping_list.extend(['chocolate', 'cake'])
print(shopping_list)
shopping_list.append('butter')
print(shopping_list)
print(type(shopping_list))
print(len(shopping_list))
print(shopping_list[0])
print(shopping_list[4])